### ISSUE TITLE
 Incomplete Contributor Guide under Community

### ISSUE THREAD

**Issue by isesteves** [physiopy/physiopy.github.io#23]
## Summary

Contributor Guide under Community with missing formatting and Table of Contents. Also some badly rendered markdown.

**Comment by isesteves** [comment]
There is no TOC yet, although now it appears on the sidebar, so maybe we don't need an in-text TOC

**Comment by smoia** [comment]
We can have it if you feel it's missing, but indeed it's on the sidebar.

**Comment by isesteves** [comment]
In the previous website it was in-text (so I included it in the issue), but I think there is no need to have it now. Feel free to close the issue.
